spring:
  application:
    name: event-driven-arch-example
  cloud:
    aws:
      credentials:
        access-key: localstack
        secret-key: localstack
      region:
        static: sa-east-1
      sqs:
        endpoint: http://localhost:4566

event-queues:
  order:
    received-events: order-received-events
    create-events: order-create-events
    failed-events: order-failed-events
    notification-events: order-notification-events
  product:
    create-events: product-create-events
    update-events: product-update-events
    notification-events: product-notification-events

push-notifications:
  product:
    creation-failed:
      title: Failed to create product {0}.
      message: Failed to create product with name {0} because {1}.
    creation-success:
      title: Product {0} created.
      message: Product with name {0} created with id {1}.
    update-failed:
      title: Product {0} couldn't be updated.
      message: Failed to update product because {1}.
    update-success:
      title: Product {0} updated.
      message: Product update successfully.
server:
  port: 8080
