spring:
  application:
    name: event-driven-arch-example
  cloud:
    aws:
      credentials:
        access-key: localstack
        secret-key: localstack
      region:
        static: sa-east-1
      sqs:
        endpoint: http://localhost:4566
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop

sqs-queues:
  product:
    commands:
      ship: product-ship-commands
    events:
      shipped: product-shipped-events
  order:
    events:
      received: order-received-events
      created: order-created-events
    commands:
      cancel: order-cancel-command
  notification:
    commands:
      notify-user: notify-user-commands

notification:
  order-products-invalid:
    title: Order will be cancelled
    message: Order {0} will be cancelled because it has invalid and/or out of stock products.
  order-products-shipped:
    title: Order products shipped
    message: All products of order {0} have been shipped.
  order-cancel-success:
    title: Order {0} cancelled
  order-cancel-fail:
    title: Failed to cancel order {0}
    message: Failed to cancell order because {0}.