version: "3.8"
services:
  localstack:
    container_name: "localstack-event-driven-arch-example"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack-scripts/create-sqs-queues.sh:/etc/localstack/init/ready.d/init-aws.sh'